### ISSUE TITLE
urth-viz-query: Add more filter comparators

### ISSUE THREAD

**Issue by dalogsdon** [peller/declarativewidgets#5]
Currently we have equals and not equals. We could add more, such as:
- contains
- not contains
- > < ≥ ≤

These could be set dynamically based on data type as well.

**Comment by peller** [comment]
@lbustelo how does one do string contains/not contains as a query?

**Comment by lbustelo** [comment]
Under the covers, the pandas support is using query(). I don't think that it supports string operations.

Gino B.

**Comment by peller** [comment]
are there any other obvious operations we could do besides inequality, or anything else type-specific to wire up?  I set it up so the inequality only works on number types...
